### Pandas - DataFrame And Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentialially heterogenous tabular data structure with labeled axes (rows and columns).

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\zahee\anakonda\envs\py312\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\zahee\anakonda\envs\py312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\zahee\anakonda\envs\py312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\zahee\anakonda\envs\py312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\zahee\anakonda\envs\py312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\zahee\anakonda\envs\py312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
## Series
## A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
## Create a Series from dictionary
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data = [10, 20, 30]
index = ['a','b','c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [17]:
## DataFrame

data = {
    'Name':['Krish', 'John', 'Zaheer'],
    'Age':[25, 30, 45],
    'City':['Banglore', 'Hyderabad', 'Riyadh']
}
dff = pd.DataFrame(data)
print(dff)
print(type(dff))

     Name  Age       City
0   Krish   25   Banglore
1    John   30  Hyderabad
2  Zaheer   45     Riyadh
<class 'pandas.core.frame.DataFrame'>

In [7]:
## Create a Data Frame From a List of Dictionaries

data = [
    {'Name': 'Zaheer', 'Age': 21, 'City': 'HYD'},
    {'Name': 'Hashid', 'Age': 20, 'City': 'KTDM'},
    {'Name': 'Asif', 'Age': 22, 'City': 'KMM'},
    {'Name': 'Rooman', 'Age': 21, 'City': 'WL'}
]
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age  City
0  Zaheer   21   HYD
1  Hashid   20  KTDM
2    Asif   22   KMM
3  Rooman   21    WL
<class 'pandas.core.frame.DataFrame'>

In [9]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

In [10]:
df.tail(5)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
3277,Karlen McCaffrey,Australia,Spicy Special Slims,17/05/2024,"$5,303.58",354
3278,Jehu Rudeforth,USA,White Choc,07/06/2024,"$7,339.32",121
3279,Ches Bonnell,Canada,Organic Choco Syrup,26/07/2024,$616.09,238
3280,Dotty Strutley,India,Eclairs,28/07/2024,"$2,504.62",397
3281,Karlen McCaffrey,India,70% Dark Bites,23/05/2024,"$5,915.87",355

In [18]:
## Accessing Data from Dataframe
dff

     Name  Age       City
0   Krish   25   Banglore
1    John   30  Hyderabad
2  Zaheer   45     Riyadh

In [21]:
dff['Name']

0     Krish
1      John
2    Zaheer
Name: Name, dtype: object

In [26]:
dff.loc[0]

Name       Krish
Age           25
City    Banglore
Name: 0, dtype: object

In [27]:
dff.iloc[0][2]

C:\Users\zahee\AppData\Local\Temp\ipykernel_60560\949802569.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dff.iloc[0][2]

'Banglore'

In [32]:
## Accessing a specified element

dff.at[1,'Age']

30

In [33]:
dff.at[2,'Name']

'Zaheer'

In [34]:
## Accessing a specified element at using iat
dff.iat[2,2]

'Riyadh'

In [35]:
### Data Manipulation with Dataframe
dff

     Name  Age       City
0   Krish   25   Banglore
1    John   30  Hyderabad
2  Zaheer   45     Riyadh

In [36]:
## Adding a column
dff['Salary'] = [50000, 60000, 70000]
dff

     Name  Age       City  Salary
0   Krish   25   Banglore   50000
1    John   30  Hyderabad   60000
2  Zaheer   45     Riyadh   70000

In [40]:
## Removing a column
dff.drop('Salary', axis=1, inplace=True)

In [41]:
dff

     Name  Age       City
0   Krish   25   Banglore
1    John   30  Hyderabad
2  Zaheer   45     Riyadh

In [44]:
## Add age to the column
dff['Age'] = dff['Age']+1
dff

     Name  Age       City
0   Krish   28   Banglore
1    John   33  Hyderabad
2  Zaheer   48     Riyadh

In [46]:
dff.drop(0, inplace=True)

In [47]:
dff

     Name  Age       City
1    John   33  Hyderabad
2  Zaheer   48     Riyadh

In [48]:
df.head(5)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

In [49]:
## Display the data types of each column
print("Data types:\n", df.dtypes)

## Describe the Dataframe
print("Statistical summary:\n", df.describe())

Data types:
 Sales Person     object
Country          object
Product          object
Date             object
Amount           object
Boxes Shipped     int64
dtype: object
Statistical summary:
        Boxes Shipped
count    3282.000000
mean      164.666971
std       124.024736
min         1.000000
25%        71.000000
50%       137.000000
75%       232.000000
max       778.000000

In [50]:
df.describe()

       Boxes Shipped
count    3282.000000
mean      164.666971
std       124.024736
min         1.000000
25%        71.000000
50%       137.000000
75%       232.000000
max       778.000000