### Data Manipulation and Analysis with Pandas

Data Manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
## Fetch the first 5 rows
df.head(5)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [3]:
df.tail(5)

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [4]:
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [5]:
df.dtypes

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [8]:
## Handling Missing Values
df.isnull().any()

Duration    False
Pulse       False
Maxpulse    False
Calories     True
dtype: bool

In [9]:
df.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [11]:
df_filled = df.fillna(0)

In [13]:
### Filling missing values with the mean of the column
df['Calories_fillNA'] = df['Calories'].fillna(df['Calories'].mean())
df

     Duration  Pulse  Maxpulse  Calories  Calories_fillNA
0          60    110       130     409.1            409.1
1          60    117       145     479.0            479.0
2          60    103       135     340.0            340.0
3          45    109       175     282.4            282.4
4          45    117       148     406.0            406.0
..        ...    ...       ...       ...              ...
164        60    105       140     290.8            290.8
165        60    110       145     300.0            300.0
166        60    115       145     310.2            310.2
167        75    120       150     320.4            320.4
168        75    125       150     330.4            330.4

[169 rows x 5 columns]

In [14]:
df.dtypes

Duration             int64
Pulse                int64
Maxpulse             int64
Calories           float64
Calories_fillNA    float64
dtype: object

In [17]:
## Renaming Columns
df = df.rename(columns={'Total_duration':'Total Duration'})
df.head()

   Total Duration  Pulse  Maxpulse  Calories  Calories_fillNA
0              60    110       130     409.1            409.1
1              60    117       145     479.0            479.0
2              60    103       135     340.0            340.0
3              45    109       175     282.4            282.4
4              45    117       148     406.0            406.0

In [19]:
## Change datatype
df['Calories_new'] = df['Calories'].fillna(df['Calories'].mean()).astype(int)
df.head()

   Total Duration  Pulse  Maxpulse  Calories  Calories_fillNA  Calories_new
0              60    110       130     409.1            409.1           409
1              60    117       145     479.0            479.0           479
2              60    103       135     340.0            340.0           340
3              45    109       175     282.4            282.4           282
4              45    117       148     406.0            406.0           406

In [20]:
df['New Calories'] = df['Calories'].apply(lambda x:x*2)
df.head()

,Total Duration,Pulse,Maxpulse,Calories,Calories_fillNA,Calories_new,New Calories
0,60,110,130,409.1,409.1,409,818.2
1,60,117,145,479.0,479.0,479,958.0
2,60,103,135,340.0,340.0,340,680.0
3,45,109,175,282.4,282.4,282,564.8
4,45,117,148,406.0,406.0,406,812.0

In [21]:
## Data Aggregating and Grouping
df.head()

,Total Duration,Pulse,Maxpulse,Calories,Calories_fillNA,Calories_new,New Calories
0,60,110,130,409.1,409.1,409,818.2
1,60,117,145,479.0,479.0,479,958.0
2,60,103,135,340.0,340.0,340,680.0
3,45,109,175,282.4,282.4,282,564.8
4,45,117,148,406.0,406.0,406,812.0

In [22]:
grouped_mean = df.groupby('Total Duration')['Pulse'].mean()
print(grouped_mean)

Total Duration
15     102.000000
20     125.000000
25     152.000000
30     109.812500
45     107.485714
60     106.126582
75     122.500000
80     123.000000
90      93.750000
120    100.000000
150    101.500000
160    109.500000
180     93.666667
210    122.500000
270    100.000000
300    108.000000
Name: Pulse, dtype: float64

In [23]:
grouped_sum = df.groupby(['Total Duration', 'Maxpulse'])['Pulse'].sum()
print(grouped_sum)

Total Duration  Maxpulse
15              100          80
                139         124
20              107          83
                112          95
                130         110
                           ...
180             130          90
210             160         108
                184         137
270             131         100
300             143         108
Name: Pulse, Length: 106, dtype: int64

In [24]:
df.groupby(['Total Duration', 'Maxpulse'])['Pulse'].mean()

Total Duration  Maxpulse
15              100          80.0
                139         124.0
20              107          83.0
                112          95.0
                130         110.0
                            ...
180             130          90.0
210             160         108.0
                184         137.0
270             131         100.0
300             143         108.0
Name: Pulse, Length: 106, dtype: float64

In [26]:
## Aggregate multiple functions
grouped_agg = df.groupby('Total Duration')['Pulse'].agg(['mean','sum','count'])
grouped_agg

                      mean   sum  count
Total Duration
15              102.000000   204      2
20              125.000000  1125      9
25              152.000000   152      1
30              109.812500  1757     16
45              107.485714  3762     35
60              106.126582  8384     79
75              122.500000   245      2
80              123.000000   123      1
90               93.750000   750      8
120             100.000000   300      3
150             101.500000   406      4
160             109.500000   219      2
180              93.666667   281      3
210             122.500000   245      2
270             100.000000   100      1
300             108.000000   108      1

In [27]:
### Merging and Joining DataFrames
# Create sample DataFrames
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [28]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [29]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [31]:
## Merge DataFrames on the 'Key Columns' 
pd.merge(df1, df2, on="Key", how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [32]:
pd.merge(df1, df2, on="Key", how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [33]:
pd.merge(df1, df2, on="Key", how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [34]:
pd.merge(df1, df2, on="Key", how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6